# Generated by Django 3.2.4 on 2023-07-10 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
