# Generated by Django 3.2.4 on 2023-07-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_conversation_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='read_by',
        ),
    ]
