name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          cd TaskNet
          python -m pip install --upgrade pip
          pip install django

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Collect static files
        run: |
          python manage.py collectstatic

      - name: Deploy code to EC2
        run: |
          scp -i TaskNetKey.pem -r TaskNet/* ubuntu@ec2-65-2-190-111.ap-south-1.compute.amazonaws.com:/path/to/destination

      - name: SSH into EC2 instance
        run: |
          ssh -i TaskNetKey.pem ubuntu@ec2-65-2-190-111.ap-south-1.compute.amazonaws.com

      - name: Restart Apache
        run: sudo service apache2 restart
